import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'qr_scanner_dialog.dart';
import '../state.dart';

class GymLinkDialog extends StatefulWidget {
  const GymLinkDialog({Key? key}) : super(key: key);

  @override
  State<GymLinkDialog> createState() => _GymLinkDialogState();
}

class _GymLinkDialogState extends State<GymLinkDialog> {
  final _codeController = TextEditingController();
  bool _isLoading = false;
  String? _statusMessage;

  Future<void> _processCode() async {
    final code = _codeController.text.trim().toUpperCase();
    if (code.isEmpty) return;

    setState(() {
      _isLoading = true;
      _statusMessage = null;
    });

    try {
      final prefs = await SharedPreferences.getInstance();

      if (code.startsWith('GYM-')) {
        final query = await FirebaseFirestore.instance
            .collection('gyms')
            .where('linkingCode', isEqualTo: code)
            .limit(1)
            .get();

        if (query.docs.isEmpty) {
          setState(() {
            _statusMessage = 'Gym code not found!';
            _isLoading = false;
          });
          return;
        }

        final gymDoc = query.docs.first;
        final gymData = gymDoc.data();
        await prefs.setString('linkedGymId', gymDoc.id);
        await prefs.setString('linkedGymName', gymData['name'] ?? 'Gym');

        setState(() {
          _statusMessage = 'Linked successfully to Gym: ${gymData['name']}!';
          _isLoading = false;
        });
      } else if (code.startsWith('TRN-')) {
        final query = await FirebaseFirestore.instance
            .collection('trainers')
            .where('linkingCode', isEqualTo: code)
            .limit(1)
            .get();

        if (query.docs.isEmpty) {
          setState(() {
            _statusMessage = 'Trainer code not found!';
            _isLoading = false;
          });
          return;
        }

        final trainerDoc = query.docs.first;
        final trainerData = trainerDoc.data();
        await prefs.setString('linkedTrainerId', trainerDoc.id);
        await prefs.setString('linkedTrainerName', trainerData['name'] ?? 'Trainer');

        setState(() {
          _statusMessage = 'Linked successfully to Trainer: ${trainerData['name']}!';
          _isLoading = false;
        });
      } else if (code.startsWith('CLI-')) {
        final query = await FirebaseFirestore.instance
            .collection('clients')
            .where('linkingCode', isEqualTo: code)
            .limit(1)
            .get();

        if (query.docs.isEmpty) {
          setState(() {
            _statusMessage = 'Client account not found!';
            _isLoading = false;
          });
          return;
        }

        final clientDoc = query.docs.first;
        final clientData = clientDoc.data();
        
        await prefs.setString('linkedClientId', clientDoc.id);
        await prefs.setString('linkedClientName', clientData['name'] ?? 'Client');
        if (clientData['gymId'] != null) {
          await prefs.setString('linkedGymId', clientData['gymId']);
        }
        if (clientData['trainerId'] != null) {
          await prefs.setString('linkedTrainerId', clientData['trainerId']);
        }

        // Trigger routine syncing instantly in background
        await GymAppState.instance.syncActiveRoutinesFromFirestore();

        setState(() {
          _statusMessage = 'Linked successfully to Client: ${clientData['name']}!';
          _isLoading = false;
        });
      } else {
        setState(() {
          _statusMessage = 'Invalid code! Code must start with GYM-, TRN-, or CLI-.';
          _isLoading = false;
        });
      }
    } catch (e) {
      setState(() {
        _statusMessage = 'Error connecting to database: $e';
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    const limeColor = Color(0xFFA3E635);
    
    return AlertDialog(
      backgroundColor: const Color(0xFF14171D),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(20),
        side: const BorderSide(color: Color(0xFF22262F)),
      ),
      title: const Text(
        'Link Gym & Trainer',
        style: TextStyle(fontFamily: 'Outfit', fontWeight: FontWeight.bold, color: Colors.white, fontSize: 18),
      ),
      content: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          const Text(
            'Enter the unique code generated by your gym dashboard (e.g. GYM-XXXX, TRN-XXXX, CLI-XXXX) or scan the QR Code on screen to sync.',
            style: TextStyle(fontSize: 13, color: Color(0xFF8E94A0)),
          ),
          const SizedBox(height: 16),
          TextField(
            controller: _codeController,
            decoration: InputDecoration(
              enabledBorder: const OutlineInputBorder(borderSide: BorderSide(color: Color(0xFF22262F))),
              focusedBorder: const OutlineInputBorder(borderSide: BorderSide(color: limeColor)),
              labelText: 'Linking Code',
              labelStyle: const TextStyle(color: Color(0xFF8E94A0), fontSize: 13),
              hintText: 'e.g. CLI-8821',
              hintStyle: const TextStyle(color: Color(0xFF5C626E), fontSize: 13),
              suffixIcon: IconButton(
                icon: const Icon(Icons.qr_code_scanner, color: limeColor),
                onPressed: () async {
                  final code = await showDialog<String>(
                    context: context,
                    builder: (context) => const QrScannerDialog(),
                  );
                  if (code != null) {
                    setState(() {
                      _codeController.text = code;
                    });
                    _processCode();
                  }
                },
              ),
            ),
            style: const TextStyle(fontSize: 14, color: Colors.white),
          ),
          if (_statusMessage != null) ...[
            const SizedBox(height: 12),
            Text(
              _statusMessage!,
              style: TextStyle(
                color: _statusMessage!.contains('successfully') ? Colors.green : Colors.red,
                fontWeight: FontWeight.bold,
                fontSize: 13,
              ),
            ),
          ],
        ],
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Cancel', style: TextStyle(color: Color(0xFF8E94A0))),
        ),
        ElevatedButton(
          style: ElevatedButton.styleFrom(
            backgroundColor: limeColor,
            foregroundColor: Colors.black,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
          onPressed: _isLoading ? null : _processCode,
          child: _isLoading
              ? const SizedBox(
                  width: 16,
                  height: 16,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
              : const Text('Link Account', style: TextStyle(fontWeight: FontWeight.bold)),
        ),
      ],
    );
  }
}
